language: python
python:
 - "2.7"

install:
 - "pip install -r requerimientos.txt"

before_script:
 - cd test/features 
 - autopep8 -ir *
 - flake8 --max-complexity=8 --exclude=*.txt,*.md,*.pyc,*.feature *

script:
  - cd ..
  - lettuce 
  - python features/areasUnitTest.py
  - coverage run --branch features/areasUnitTest.py
  - coverage report -m